services:
  worker:
    gpus: all
    environment:
      FFMPEG_VIDEO_ENCODER: ${FFMPEG_VIDEO_ENCODER:-hevc_nvenc}
      FFMPEG_HWACCEL: ${FFMPEG_HWACCEL:-cuda}
      NVIDIA_VISIBLE_DEVICES: ${NVIDIA_VISIBLE_DEVICES:-all}
      NVIDIA_DRIVER_CAPABILITIES: ${NVIDIA_DRIVER_CAPABILITIES:-compute,video,utility}
